services:
  postgres:
    container_name: jatoda_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: Jatoda
      POSTGRES_USER: sergejnehorosev
      POSTGRES_PASSWORD: 895318
    ports:
      - "5432:5432"
    volumes:
      - jatoda_postgres_data:/var/lib/postgresql/data

  redis:
    container_name: jatoda_redis
    image: redis:latest
    ports:
      - "6379:6379"

  minio:
    container_name: jatoda_minio
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: ACCESSKEY
      MINIO_SECRET_KEY: Jatoda-Object-Storage
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - jatoda_minio_data:/data

  elasticsearch:
    container_name: jatoda_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:latest
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    volumes:
      - jatoda_elasticsearch_data:/usr/share/elasticsearch/data
  
  kibana:
    container_name: jatoda_kibana
    image: docker.elastic.co/kibana/kibana:latest
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5193:5193"
    depends_on:
      - postgres
      - redis
      - minio
      - elasticsearch

volumes:
  jatoda_postgres_data:
  jatoda_redis_data:
  jatoda_minio_data:
  jatoda_elasticsearch_data: